services:
  # 1. El Servicio de Base de Datos
  mongodb:
    #image: mongo:7.0.4
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db  # <--- ¡Aquí salvamos los datos!

  # 2. Nuestra Aplicación (Product Service)
  #  product-service:
  #    build: .              # Usa el Dockerfile de la carpeta actual
  #    container_name: product-service
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      # Sobrescribimos la config de Spring para usar Docker
  #      # Fíjate: usamos 'mongodb' en lugar de 'localhost'
  #      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/${MONGO_DATABASE}?authSource=${MONGO_AUTH_DB}
  #    depends_on:
  #      - mongodb           # Espera a que la BD arranque primero

  #------------------ 3. Nuestra Aplicación (Inventory DB Mysql)
  inventory-db:
    image: mysql:latest
    container_name: inventory-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - inventory_data:/var/lib/mysql


  #----------------- 4. Nuestra Aplicación (Order DB Postgresql)
  order-db:
    image: postgres:17.1-alpine
    container_name: order-db-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  #-------------------------- Authentication Service
  keycloak-db:
    image: postgres:17.1-alpine
    container_name: keycloak-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_LOGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_LOGIN}
      POSTGRES_DB: ${POSTGRES_DB_LOGIN}
    ports:
      - "5433:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data
  #    healthcheck:
  #      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_LOGIN} -d ${POSTGRES_DB_LOGIN}"]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5

  #--------------------------  Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command: start-dev # Modo desarrollo (rápido y sin HTTPS obligatorio)
    restart: always
    environment:
      KC_DB: postgres # Vendor de la base de datos
      KC_DB_URL: jdbc:postgresql://${POSTGRES_DB_LOGIN}:5432/${POSTGRES_DB_LOGIN}
      KC_DB_USERNAME: ${POSTGRES_USER_LOGIN}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD_LOGIN}
      # Credenciales del Super Admin (Para entrar a la consola ya mismo)
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
  #--------------------------  RabbitMq
  rabbitmq:
    #image: rabbitmq:3-management
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Puerto para comunicación entre microservicios
      - "15672:15672" # Puerto para la consola de gestión web
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # <--- ¡La persistencia!
  #--------------------------  grafana Opentelemetry
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    environment:
      - OTEL_METRIC_EXPORT_INTERVAL=5000
volumes:
  mongo_data:             # Declaramos el volumen persistente
  inventory_data:
  order_data:
  keycloak_data:
  rabbitmq_data: