spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    fetchRegistry: true
    registerWithEureka: true
server:
  port: ${SERVER_PORT_GATEWAY}

