spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms # Primera espera de 3 segundos
          max-attempts: 3          # Máximo 3 intentos totales
          max-interval: 10000ms   # No esperar más de 10 segundos
          multiplier: 2.0         # Backoff exponencial (3s, 6s, 10s)
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_TRAP_USER} # <--- Pega tu usuario aquí
    password: ${MAIL_TRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  tracing:
    sampling:
      probability: 1.0  # Captura el 100% de las trazas para desarrollo
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OPENTELEMETRY_OTLP_ENDPOINT}/traces
    logging:
      export:
        otlp:
          endpoint: ${OPENTELEMETRY_OTLP_ENDPOINT}/logs
  otlp:
    metrics:
      export:
        url: ${OPENTELEMETRY_OTLP_ENDPOINT}/metrics
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    fetchRegistry: true
    registerWithEureka: true
logging:
  # ✅ CORRELACIÓN DE LOGS (TraceID y SpanID en consola de IntelliJ/Docker)
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
  level:
    root: INFO
    com.ecommerce: INFO
server:
  port: ${SERVER_PORT_NOTIFICATION}