spring:
  threads:
    virtual:
      enabled: true
  mongodb:
    #    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=${MONGO_AUTH_DB}
    #    database: ${MONGO_DATABASE}
    # Sintaxis: ${NOMBRE_VAR_ENTORNO : VALOR_POR_DEFECTO}
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DATABASE}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTH_DB}
  web:
    error:
      include-message: always
      include-stacktrace: never
      #que siempre vaya el message y que nunca vaya en la respuesta json el print stracTrace
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    fetchRegistry: true
    registerWithEureka: true
# variables de entorno, nada que ver con spring boot
app:
  maintenance:
    message: ${MAINTENANCE_MESSAGE}
# actuator
management:
  endpoints:
    web:
      exposure:
        # incluye endpoints por defecto
        include: "refresh, health"
server:
  port: ${SERVER_PORT_PRODUCTS}

