spring:
  application:
    name: product-service
  threads:
    virtual:
      enabled: true
  mongodb:
    #    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=${MONGO_AUTH_DB}
    #    database: ${MONGO_DATABASE}
    # Sintaxis: ${NOMBRE_VAR_ENTORNO : VALOR_POR_DEFECTO}
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DATABASE}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTH_DB}
  web:
    error:
      include-message: always
      include-stacktrace: never
      #que siempre vaya el message y que nunca vaya en la respuesta json el print stracTrace
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    fetchRegistry: true
    registerWithEureka: true
# variables de entorno, nada que ver con spring boot
app:
  maintenance:
    message: ${MAINTENANCE_MESSAGE}
# actuator
management:
  tracing:
    sampling:
      probability: 1.0  # Captura el 100% de las trazas para desarrollo
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OPENTELEMETRY_OTLP_ENDPOINT}/traces
    logging:
      export:
        otlp:
          endpoint: ${OPENTELEMETRY_OTLP_ENDPOINT}/logs
  otlp:
    metrics:
      export:
        url: ${OPENTELEMETRY_OTLP_ENDPOINT}/metrics
  endpoints:
    web:
      exposure:
        # incluye endpoints por defecto
        include: "refresh, health, prometheus"
# ✅ CORRELACIÓN DE LOGS (TraceID y SpanID en consola de IntelliJ/Docker)
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
server:
  port: ${SERVER_PORT_PRODUCTS}

