spring:
  application:
    name: discovery-server
server:
  port: ${SERVER_PORT_DISCOVERY}
eureka:
  client:
    register-with-eureka: false
#    fetch registry false le dice que no sincronice datos
    fetch-registry: false